### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Ikuyu** [jangko/nim-noise#13]
In my code I use the same order as the Readme:

- Load history
- Set prompt
- Set completion hook
- Start loop to read lines

When I hit TAB (as the first character) on a line I get a runtime error.

<img width="723" alt="Screen Shot 2020-10-22 at 10 41 43 AM" src="https://user-images.githubusercontent.com/57272868/96847220-33de9b80-1453-11eb-9f68-2e07e704c1b4.png">

**Comment by js-on** [comment]
Facing the same issue.

#### Steps to reproduce
1. Installed Nim Version
```
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release
```
2. Install noise@0.1.4 via `nimble install noise`
3. Compile examples/test.nim `nim c examples/test.nim`
5. Run application `./examples/test`, hit return (to remove Superman) and then Tab
6. Application crashes with the following traceback:
```
Second Row> fatal.nim(53)            sysFatal
Error: unhandled exception: index -1 not in 0 .. 4095 [IndexDefect]
```
<hr>
The same happens on Windows 10 with Nim 1.4.8 and noise@0.1.4 returning the following traceback:

```
Second Row> C:\Users\*****\Documents\Nim\sploitus\src\sploitus.nim(98) sploitus
C:\Users\*****\Documents\Nim\sploitus\src\sploitus.nim(82) main
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise.nim(194) readLine
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise.nim(141) getInputLine
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise.nim(104) keyProcessing
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise\editorImpl.nim(48) lineCompletion
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise\editorImpl.nim(12) completeLine  
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise\lineImpl.nim(325) breakWord      
C:\Users\*****\.nimble\pkgs\noise-0.1.4\noise\lineImpl.nim(317) validChar      
C:\Users\*****\Downloads\nim-1.4.8\lib\system\fatal.nim(49) sysFatal
Error: unhandled exception: index -1 not in 0 .. 4095 [IndexDefect]
```

**Comment by jangko** [comment]
I cannot reproduce it
