### ISSUE TITLE
Small feature request

### ISSUE THREAD

**Issue by Ikuyu** [jangko/nim-noise#14]
CTRL-C is used to abort a line/the program. It would be nice if the ESC-key can also be used in this context. But then readLine should return something else then a bool.

One should be able to use the ESC-key to cancel some user input (soft abort) and CTRL-C to abort the program (hard abort).

**Comment by jangko** [comment]
you can use the new feature after #16 merged.

please compile it with `-d:esc_exit_editing` compiler switch

```nim
  while true:
    let ok = noise.readLine()
    if not ok: break

    if noise.getKeyType == ktEsc:
      echo "do something"
```
